PUT http://localhost:3000/api/productos/6744d85b86f7082aa6d5d476
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMyNTcyNzgxLCJleHAiOjE3MzI1NzYzODF9.jHo1Ru41KVqqzKvwwKAWvFlHPhIKq0QoQ3pXPQse_Fk

{
    "data":{
    "title": "Pantalon Cargo con Bolsillos",
    "description": "Prendas inferiores",
    "image": "../img",
    "status": true,
    "alt": "Pantalon Cargo",
    "link": "",
    "price": 180000,
    "amount": 26,
    "category": "6744d74086f7082aa6d5d472"
    }
  }